# Generated by Django 3.2.20 on 2023-09-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_date',
            new_name='published_date',
        ),
    ]
